/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ryan_imagedection_LibImgFun */

#ifndef _Included_com_example_ryan_imagedection_LibImgFun
#define _Included_com_example_ryan_imagedection_LibImgFun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ryan_imagedection_LibImgFun
 * Method:    imgFun
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ryan_imagedection_LibImgFun_imgFun
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_example_ryan_imagedection_LibImgFun
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ryan_imagedection_LibImgFun_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
